// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// my_CppFunction
NumericVector my_CppFunction(NumericVector x0, Function lossf, Function func1, Function func2, float epsilon, float sigma, float gamma, int MAX_ITER);
RcppExport SEXP _SA24204127_my_CppFunction(SEXP x0SEXP, SEXP lossfSEXP, SEXP func1SEXP, SEXP func2SEXP, SEXP epsilonSEXP, SEXP sigmaSEXP, SEXP gammaSEXP, SEXP MAX_ITERSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x0(x0SEXP);
    Rcpp::traits::input_parameter< Function >::type lossf(lossfSEXP);
    Rcpp::traits::input_parameter< Function >::type func1(func1SEXP);
    Rcpp::traits::input_parameter< Function >::type func2(func2SEXP);
    Rcpp::traits::input_parameter< float >::type epsilon(epsilonSEXP);
    Rcpp::traits::input_parameter< float >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< float >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type MAX_ITER(MAX_ITERSEXP);
    rcpp_result_gen = Rcpp::wrap(my_CppFunction(x0, lossf, func1, func2, epsilon, sigma, gamma, MAX_ITER));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _SA24204127_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SA24204127_my_CppFunction", (DL_FUNC) &_SA24204127_my_CppFunction, 8},
    {"_SA24204127_rcpp_hello_world", (DL_FUNC) &_SA24204127_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_SA24204127(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
