# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title 使用Rcpp的外罚函数法
#' @description 使用Rcpp的外罚函数法
#' @param x0 初始值
#' @param lossf 目标函数
#' @param func1 步骤一函数
#' @param func2 步骤二函数
#' @param epsilon 算法参数
#' @param sigma 算法参数
#' @param gamma 算法参数
#' @param MAX_ITER 最大迭代次数
#' @return 最优值
#' @export
my_CppFunction <- function(x0, lossf, func1, func2, epsilon = 1e-6, sigma = 0.5, gamma = 1.1, MAX_ITER = 1000L) {
    .Call('_SA24204127_my_CppFunction', PACKAGE = 'SA24204127', x0, lossf, func1, func2, epsilon, sigma, gamma, MAX_ITER)
}

rcpp_hello_world <- function() {
    .Call('_SA24204127_rcpp_hello_world', PACKAGE = 'SA24204127')
}

